/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnggotaRouteImport } from './routes/anggota'
import { Route as IndexRouteImport } from './routes/index'

const AnggotaRoute = AnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anggota'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anggota'
  id: '__root__' | '/' | '/anggota'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaRoute: typeof AnggotaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/anggota': {
      id: '/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaRoute: AnggotaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
