/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as KejadianRouteImport } from './routes/kejadian'
import { Route as KasRouteImport } from './routes/kas'
import { Route as AnggotaRouteImport } from './routes/anggota'
import { Route as IndexRouteImport } from './routes/index'

const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const KejadianRoute = KejadianRouteImport.update({
  id: '/kejadian',
  path: '/kejadian',
  getParentRoute: () => rootRouteImport,
} as any)
const KasRoute = KasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnggotaRoute = AnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/kas': typeof KasRoute
  '/kejadian': typeof KejadianRoute
  '/peta': typeof PetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/kas': typeof KasRoute
  '/kejadian': typeof KejadianRoute
  '/peta': typeof PetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anggota': typeof AnggotaRoute
  '/kas': typeof KasRoute
  '/kejadian': typeof KejadianRoute
  '/peta': typeof PetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/anggota' | '/kas' | '/kejadian' | '/peta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/anggota' | '/kas' | '/kejadian' | '/peta'
  id: '__root__' | '/' | '/anggota' | '/kas' | '/kejadian' | '/peta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnggotaRoute: typeof AnggotaRoute
  KasRoute: typeof KasRoute
  KejadianRoute: typeof KejadianRoute
  PetaRoute: typeof PetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kejadian': {
      id: '/kejadian'
      path: '/kejadian'
      fullPath: '/kejadian'
      preLoaderRoute: typeof KejadianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kas': {
      id: '/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof KasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anggota': {
      id: '/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AnggotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnggotaRoute: AnggotaRoute,
  KasRoute: KasRoute,
  KejadianRoute: KejadianRoute,
  PetaRoute: PetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
