ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS bio TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS notif_sos BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notif_kas BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notif_pengumuman BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS notif_email BOOLEAN NOT NULL DEFAULT false;